name: Pokemon Center Drop Checker

on:
  schedule:
    - cron: "*/30 * * * *"  # run every 30 minutes
  workflow_dispatch:        # allows manual run from GitHub UI

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install requests beautifulsoup4
      - run: python bot.py
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
